name: "Multi event pipeline / workflow" #Name of the pipeline

on:
    push: # Event: Whenever a push is made to the repository on the master branch
        branches:
            - master
            - test
    pull_request: #Event: Whenever a pull request is made to the repository
        branches:
            - master

jobs:
    on-push: # Job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: #Step to be executed in the job
            - name: "Running on master/test push"
              run: echo "Running on master/test push"

    on-pull-request: #Job name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"

        